apiVersion: v1
kind: PersistentVolume

metadata:
  name: app-db-pv
  labels:
    name: app-db-pv

spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data
