apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30008
        hostPort: 30008
        protocol: TCP
  - role: control-plane
  - role: worker
  - role: worker
